# Generated by Django 2.2.4 on 2020-12-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quote_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(default={}, related_name='liked_quotes', to='app.User'),
        ),
    ]
